### ISSUE TITLE
workerpool-controller - question regarding metrics service

### ISSUE THREAD

**Issue by d-mankowski-synerise** [spacelift-io/spacelift-helm-charts#67]
Hello, I have a few questions regarding workpool controller metrics service.

1. In [values.yaml](https://github.com/spacelift-io/spacelift-helm-charts/blob/main/spacelift-workerpool-controller/values.yaml#L66), key `metricsService` suggests that metrics are exposed at HTTPS `8443` port, while [deployment template](https://github.com/spacelift-io/spacelift-helm-charts/blob/main/spacelift-workerpool-controller/templates/deployment.yaml#L61) suggests that the metrics are exposed at `127.0.0.1:8080`
2. If `8443` is the right port - then how do we pass certs to Prometheus instance? And if it is wrong and `8080` is the correct one, then the binding address should not be `127.0.0.1`, but `0.0.0.0` or `${POD_IP}`. In case of localhost, Prometheus would have to run in the same pod as controller. Also, port `8080` is not added to the [ports](https://github.com/spacelift-io/spacelift-helm-charts/blob/main/spacelift-workerpool-controller/templates/deployment.yaml#L51) list.
3. There is no resource of type `ServiceMonitor` in the chart templates

**Comment by Apollorion** [comment]
Hey @d-mankowski-synerise,

to answer your questions:

1. The metricsService in values.yaml points to the `metrics` targetPort on the resulting pod. The pod is broadcasting on 8080 but its exposed on 8443 within the service itself.

2. 8443 is the correct port for the service. 8080, on the pod, is in the ports list [here](https://github.com/spacelift-io/spacelift-helm-charts/blob/main/spacelift-workerpool-controller/templates/deployment.yaml#L76).

3. The `ServiceMonitor` should be defined by the customer, which is why we've not included it in the helm chart.

Is this helpful? Anything else I can clarify?
